name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: test
        run: echo "test-success"
